# Commands to start on workspace startup
image:
  file: .gitpod.Dockerfile

tasks:

  # start tidb on local env
  - name: tiup playground (tidb unistore)
    command: |
      mkdir -p $USER/.tiup/data/
      $USER/.tiup/components/tidb/v6.1.1/tidb-server -P 4000 --store=unistore --host=127.0.0.1 --status=10080 --log-file=$USER/.tiup/data/tidb.log

  # wait tidb start
  - name: wait for tidb started
    command: gp ports await 10080 && gp sync-done tidbstarted

  # backend server (API server)
  - name: backend
    before: |
      gp sync-await tidbstarted
      composer instal
      composer update colopl/laravel-tidb
    init: |
      cp .env.example .env
      php artisan key:generate
      echo yes | php artisan jwt:secret
    command: |
      php artisan serve --host 0.0.0.0

  # web frontend
  - name: frontend
    before: |
      gp ports await 8000
    command: |
      echo todo : run frontend server

# Ports to expose on workspace startup
ports:
  - port: 4000
    onOpen: ignore
    name: TiDB
    description: TiDB
  - port: 8000
    onOpen: open-browser
    name: backend
    description: backend
  - port: 8080
    onOpen: open-browser
    name: frontend
    description: frontend
